import { ActionTypes } from "./types";

const actionTypes: ActionTypes = {
  HIDE_IMAGE: "HIDE_IMAGE",
  INITIALIZE_FILTER: "INITIALIZE_FILTER",
  RESET_IMAGES: "RESET_IMAGES",
  SHOW_IMAGE: "SHOW_IMAGE",
  UNINITIALIZE_FILTER: "UNINITIALIZE_FILTER",
  UPDATE_FILTER_OPTIONS: "UPDATE_FILTER_OPTIONS",
  UPDATE_GRID: "UPDATE_GRID",
  UPDATE_IMAGES: "UPDATE_IMAGES",
  UPDATE_LOADING: "UPDATE_LOADING",
  UPDATE_RESULTS: "UPDATE_RESULTS",
  UPDATE_RESULT_STREAM: "UPDATE_RESULT_STREAM",
  UPDATE_SCREEN_TYPE: "UPDATE_SCREEN_TYPE",
  UPDATE_SELECTED_THEME: "UPDATE_SELECTED_THEME",
  UPDATE_SELECTION: "UPDATE_SELECTION",
  UPDATE_THEMES: "UPDATE_THEMES",
};
export default actionTypes;
