import { AllFilterOptions } from "./types";

const filterOptions: AllFilterOptions = {
  animals: [
    "ant",
    "bear",
    "lion",
    "horse",
    "deer",
    "snake",
    "lizard",
    "hyppo",
    "monkey",
    "cow",
    "duck",
  ],
  cars: [
    "Audi",
    "Chevrolet",
    "Ford",
    "Toyota",
    "BMW",
    "Mercedes",
    "Subaru",
    "Mitsubishi",
    "Jeep",
    "Volkswagen",
    "Fiat",
  ],
  cities: [
    "Austin",
    "Dallas",
    "Denver",
    "Manhattan",
    "Brooklyn",
    "San Francisco",
    "Portland",
    "Seattle",
    "Boston",
    "Chicago",
    "Detroit",
  ],
  fruits: [
    "kiwi",
    "strawberry",
    "banana",
    "orange",
    "cherry",
    "pinapple",
    "peach",
    "tangerine",
    "pear",
    "dragon fruit",
    "melon",
  ],
  foods: [
    "pasta",
    "pizza",
    "hamburger",
    "fried rice",
    "noodles",
    "tacos",
    "fried chicken",
    "sandwich",
    "soup",
    "steak",
    "salad",
  ],
  sports: [
    "bmx",
    "basketball",
    "soccer",
    "chess",
    "tennis",
    "skateboarding",
    "football",
    "baseball",
    "swimming",
    "mountain biking",
    "snowboarding",
  ],
};

export default filterOptions;
